### PR TITLE
Pm 2022 09 rm planifolia

### PR DESCRIPTION
**Pull request by phillimorland**
this is ready for a first look over, as it's so much I might do the second round in a new pr.
still to-do

- [ ] inline forms to be fixed including widget
- [ ] update a4 templates so extends can be removed
- [ ] update check for further obsolete code
- [ ] anything that is picked up during review

### CODE REVIEW

**Review by fuzzylogic2000 — COMMENTED** [review]
Changes look good, but it's not isntalling or running for me with 
```
ERROR in ./meinberlin/assets/scss/style.scss (./meinberlin/assets/scss/style.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].use[2]!./node_modules/sass-loader/dist/cjs.js!./meinberlin/assets/scss/style.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable: "$gutters".
        on line 114 of node_modules/bootstrap/scss/mixins/_grid.scss, in mixin `@content`
        from line 68 of node_modules/bootstrap/scss/mixins/_breakpoints.scss, in mixin `media-breakpoint-up`
        from line 72 of node_modules/bootstrap/scss/mixins/_grid.scss, in mixin `make-grid-columns`
        from line 32 of node_modules/bootstrap/scss/_grid.scss
        from line 9 of meinberlin/assets/scss/style.scss
>>       @each $key, $value in $gutters {

   ----------------------------^

SassError: SassError: Undefined variable: "$gutters".
        on line 114 of node_modules/bootstrap/scss/mixins/_grid.scss, in mixin `@content`
        from line 68 of node_modules/bootstrap/scss/mixins/_breakpoints.scss, in mixin `media-breakpoint-up`
        from line 72 of node_modules/bootstrap/scss/mixins/_grid.scss, in mixin `make-grid-columns`
        from line 32 of node_modules/bootstrap/scss/_grid.scss
        from line 9 of meinberlin/assets/scss/style.scss
>>       @each $key, $value in $gutters {

   ----------------------------^

    at Object.loader (/home/katharina/a4-meinberlin/node_modules/sass-loader/dist/index.js:69:14)
 @ ./meinberlin/assets/scss/style.scss

ERROR in ./meinberlin/assets/scss/style.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable: "$gutters".
        on line 114 of node_modules/bootstrap/scss/mixins/_grid.scss, in mixin `@content`
        from line 68 of node_modules/bootstrap/scss/mixins/_breakpoints.scss, in mixin `media-breakpoint-up`
        from line 72 of node_modules/bootstrap/scss/mixins/_grid.scss, in mixin `make-grid-columns`
        from line 32 of node_modules/bootstrap/scss/_grid.scss
        from line 9 of meinberlin/assets/scss/style.scss
>>       @each $key, $value in $gutters {

   ----------------------------^

    at tryRunOrWebpackError (/home/katharina/a4-meinberlin/node_modules/webpack/lib/HookWebpackError.js:88:9)
    at __webpack_require_module__ (/home/katharina/a4-meinberlin/node_modules/webpack/lib/Compilation.js:5055:12)
    at __webpack_require__ (/home/katharina/a4-meinberlin/node_modules/webpack/lib/Compilation.js:5012:18)
    at /home/katharina/a4-meinberlin/node_modules/webpack/lib/Compilation.js:5083:20
    at symbolIterator (/home/katharina/a4-meinberlin/node_modules/neo-async/async.js:3485:9)
    at done (/home/katharina/a4-meinberlin/node_modules/neo-async/async.js:3527:9)
    at Hook.eval [as callAsync] (eval at create (/home/katharina/a4-meinberlin/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/katharina/a4-meinberlin/node_modules/webpack/lib/Compilation.js:4990:43
    at symbolIterator (/home/katharina/a4-meinberlin/node_modules/neo-async/async.js:3482:9)
    at timesSync (/home/katharina/a4-meinberlin/node_modules/neo-async/async.js:2297:7)
-- inner error --
Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable: "$gutters".
        on line 114 of node_modules/bootstrap/scss/mixins/_grid.scss, in mixin `@content`
        from line 68 of node_modules/bootstrap/scss/mixins/_breakpoints.scss, in mixin `media-breakpoint-up`
        from line 72 of node_modules/bootstrap/scss/mixins/_grid.scss, in mixin `make-grid-columns`
        from line 32 of node_modules/bootstrap/scss/_grid.scss
        from line 9 of meinberlin/assets/scss/style.scss
>>       @each $key, $value in $gutters {

   ----------------------------^

    at Object.<anonymous> (/home/katharina/a4-meinberlin/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].use[1]!/home/katharina/a4-meinberlin/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].use[2]!/home/katharina/a4-meinberlin/node_modules/sass-loader/dist/cjs.js!/home/katharina/a4-meinberlin/meinberlin/assets/scss/style.scss:1:7)
    at /home/katharina/a4-meinberlin/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:441:11
    at Hook.eval [as call] (eval at create (/home/katharina/a4-meinberlin/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at /home/katharina/a4-meinberlin/node_modules/webpack/lib/Compilation.js:5057:39
    at tryRunOrWebpackError (/home/katharina/a4-meinberlin/node_modules/webpack/lib/HookWebpackError.js:83:7)
    at __webpack_require_module__ (/home/katharina/a4-meinberlin/node_modules/webpack/lib/Compilation.js:5055:12)
    at __webpack_require__ (/home/katharina/a4-meinberlin/node_modules/webpack/lib/Compilation.js:5012:18)
    at /home/katharina/a4-meinberlin/node_modules/webpack/lib/Compilation.js:5083:20
    at symbolIterator (/home/katharina/a4-meinberlin/node_modules/neo-async/async.js:3485:9)
    at done (/home/katharina/a4-meinberlin/node_modules/neo-async/async.js:3527:9)

Generated code for /home/katharina/a4-meinberlin/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].use[1]!/home/katharina/a4-meinberlin/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].use[2]!/home/katharina/a4-meinberlin/node_modules/sass-loader/dist/cjs.js!/home/katharina/a4-meinberlin/meinberlin/assets/scss/style.scss
1 | throw new Error("Module build failed (from ./node_modules/sass-loader/dist/cjs.js):\nSassError: Undefined variable: \"$gutters\".\n        on line 114 of node_modules/bootstrap/scss/mixins/_grid.scss, in mixin `@content`\n        from line 68 of node_modules/bootstrap/scss/mixins/_breakpoints.scss, in mixin `media-breakpoint-up`\n        from line 72 of node_modules/bootstrap/scss/mixins/_grid.scss, in mixin `make-grid-columns`\n        from line 32 of node_modules/bootstrap/scss/_grid.scss\n        from line 9 of meinberlin/assets/scss/style.scss\n>>       @each $key, $value in $gutters {\n\n   ----------------------------^\n");
```

**Comment by phillimorland** [comment]
@fuzzylogic2000 can't trigger error, was it just a normal `make clean` and `install`?

**Comment by fuzzylogic2000** [comment]
> @fuzzylogic2000 can't trigger error, was it just a normal `make clean` and `install`?

Yes, I did also do the installation on main and then only run `make watch` in your branch and also got these errors. Will delete your branch and refetch to make sure, that wasn't an old version!

**Comment by phillimorland** [comment]
@fuzzylogic2000 tried updating import order and it's pushed, no clue why it works locally?!

**Comment by phillimorland** [comment]
@fuzzylogic2000 now passing!

**Pull request merged**
