### PR TITLE
Pm 2019 02 list width

### PR DESCRIPTION
**Pull request by phillimorland**
bit annoying having to add - margin but i think it's better than trying to remove just the outer margins on the tiles?

### CODE REVIEW

**Comment by phillimorland** [comment]
huh I'll take another look, was that chrome?

**Comment by phillimorland** [comment]
ok that is hopefully fixed!

**Comment by phillimorland** [comment]
it very much is! um fuck

**Comment by phillimorland** [comment]
can't reproduce error in chromium, @fuzzylogic2000 was that browser you were using?

**Comment by fuzzylogic2000** [comment]
Haha! Today it's gone! So, it was my cache... Sorry!

**Pull request merged**
