### PR TITLE
package.json: Update babel

### PR DESCRIPTION
**Pull request by treba123**
This should allow us to use ES6/2015 features.

And some drive-by additions

### CODE REVIEW

**Comment by treba123** [comment]
em vs rem error... @fuzzylogic2000 can you have a look when you have time?

**Comment by treba123** [comment]
Seems to be because I updated bootstrap as a drive-by (security warning...)

**Comment by MagdaN** [comment]
I get the same error as in the other project (euth): Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Module.eval (Modal.jsx:61)

**Comment by treba123** [comment]
Alright, in the end everything turned out to be much simpler than expected...but some lessons learned :)
This should work now and the solution should be easily portable to all our projects without changes to .jsx files

**Pull request merged**
