### PR TITLE
map: remove color from icons in ideas map display

### PR DESCRIPTION
**Pull request by vellip**

### CODE REVIEW

**Comment by vellip** [comment]
@m4ra let me know if we should change the a4 commit hash in this PR directly or not. Regardless it should also be in the release.

**Comment by m4ra** [comment]
Yes, please change the commit hash of a4 so PMs can test it in dev.

**Comment by vellip** [comment]
@m4ra Do you already have a release branch in a4?

**Comment by m4ra** [comment]
No, I can do that quickly, one minute

**Comment by m4ra** [comment]
@vellip you can update the a4 dependency here with the following `liqd/adhocracy4#mB-v2412.2`

**Comment by vellip** [comment]
@m4ra  I just did. One second before merging though, because for some reason I still have the `aural` css class on comments.
CleanShot 2024-12-18 at 12 55 12@2x

**Comment by vellip** [comment]
@m4ra sorry, I am a bit slow today... somehow the change that I did here https://github.com/liqd/adhocracy4/pull/1736/commits/ae6b657cd3a8a01f27637dcca4d89c91a4a44927 doesn't seem to be in my version of a4 after running `make install` even after setting the release branch as target for install. But maybe that's just a local issue with my installation?

**Comment by vellip** [comment]
should be good now, thanks @m4ra

**Review by m4ra — APPROVED** [review]
Thanks, I will merge once workflow tests are done.

**Pull request merged**
