### PR TITLE
Pm 2022 09 pagination js basic

### PR DESCRIPTION
**Pull request by phillimorland**
incomplete functionality

- [x] limit number of pages shown to 1 either side of active and first and last
- [x] show `...` element when there is a gap between siblings of active page and first or last (see django pagination)

### CODE REVIEW

**Comment by fuzzylogic2000** [comment]
@khamui you are going on with this one, right? So I will assign you!

**Comment by khamui** [comment]
using the current state, which worked fine. Cleaned up and restructured it to make future work (and tests) easier.
Currently on the missing part (`...` and the logic around the active `PaginationButton`). Not sure if there is a way to get it from Backend (Django Pagination Logic) or we need to mimic this behavior in frontend.

**Comment by Rineee** [comment]
@khamui There seem to be still some little differences, see screenshot (the arrows are missing for less page sizes and the selected page isnt highlighted in blue)

image

**Comment by khamui** [comment]
@Rineee hum, i doublechecked on my side and it looks fine. i guess you git fetched the latest branch?

Bildschirmfoto 2022-09-14 um 15 14 21

**Comment by Rineee** [comment]
> @Rineee hum, i doublechecked on my side and it looks fine. i guess you git fetched the latest branch?
> 
> Bildschirmfoto 2022-09-14 um 15 14 21

Oh ok, sorry for the confusion then! I did fetch the latest branch, yes. Will check again!

**Review by Rineee — APPROVED** [review]
It looks good now, dont know what I did before, sorry! 

Maybe @fuzzylogic2000 can also have a look!

**Review by fuzzylogic2000 — APPROVED** [review]
Very nice!

**Pull request merged**
