### PR TITLE
[7409] budgeting 1+2 support

### PR DESCRIPTION
**Pull request by goapunk**

### CODE REVIEW

**Comment by Rineee** [comment]
@goapunk This should be ready, could not request review as its your PR

**Comment by Rineee** [comment]
will fix tests

**Comment by Rineee** [comment]
I am still trying to test the new `ProposalDashboardExportView` in views.py, but could not make it work so far, so I thought we could already merge this, so we can go on?

**Comment by Rineee** [comment]
> @Rineee the other stories don't depend on this one, do they? So we don't really need to rush this. In any case it looks good to me! I added a commit to update the fixtures so they use the new phases. Maybe you can have a quick look and then we merge

Well the next one in backlog does and as the other one in the sprint depends on the form story, I thought we might need it! But turns out no :stuck_out_tongue_closed_eyes: 

Maybe @fuzzylogic2000 or @philli-m can also have a quick look as we both worked on this?

Fixture looks good to me!

**Comment by philli-m** [comment]
@Rineee it's looking good to me, think @fuzzylogic2000 is a better bet to check the code though as I don't get all of it

**Review by fuzzylogic2000 — APPROVED** [review]
Cool!

**Pull request merged**
