### PR TITLE
Ks 2022 09 module type fixes

### PR DESCRIPTION
**Pull request by Rineee**
I could not find anything else to fix, also looked into templates.. we will probably find more later!

### CODE REVIEW

**Comment by Rineee** [comment]
Oh no, will fix test on Monday.. although it does not fail locally, which is weird

**Review by fuzzylogic2000 — APPROVED** [review]
Looks great!
Should we merge now or after adding more tests? :)

**Comment by Rineee** [comment]
> Looks great! Should we merge now or after adding more tests? :)

Hm, I did not really add anything, why did the coverage go down? Its mostly the get_progress in the dashboard components, that is now not covered anymore, can investigate why that is and if I can add tests..

**Comment by fuzzylogic2000** [comment]
> > Looks great! Should we merge now or after adding more tests? :)
> 
> Hm, I did not really add anything, why did the coverage go down? Its mostly the get_progress in the dashboard components, that is now not covered anymore, can investigate why that is and if I can add tests..

Let's just go craaazy and merge without the tests! :rofl:

**Pull request merged**
