### PR TITLE
apps/votes/views: use gettext_lazy instead of gettext to fix tests

### PR DESCRIPTION
**Pull request by Rineee**
Without the laziness :), the translation.override does not work.. https://docs.djangoproject.com/en/4.1/topics/i18n/translation/#lazy-translation

### CODE REVIEW

**Comment by goapunk** [comment]
@Rineee tests are still failing

**Comment by Rineee** [comment]
> @Rineee tests are still failing

Wtf, before they were only failing locally and now they are only failing in the ci?

**Comment by Rineee** [comment]
> > @Rineee tests are still failing
> 
> Wtf, before they were only failing locally and now they are only failing in the ci?

Ok, so in the export we need to use gettext, so I moved it to its own file now  :woman_shrugging:

**Review by fuzzylogic2000 — APPROVED** [review]
Cool!
You could also only import one of these as `_` and use the other one just with it's name. But this is also fine!

**Pull request merged**
