### PR TITLE
Send form submissions as xlsx instead of csv

### PR DESCRIPTION
**Pull request by 2e2a**

### CODE REVIEW

**Comment by kleingeist** [comment]
newlines in multiline fields are displayed as _x000D_
```
Hello_x000D_
Multi_x000D_
💩
```

**Comment by 2e2a** [comment]
> newlines in multiline fields are displayed as x000D

pushed a fix

**Comment by 2e2a** [comment]
fixed the fix

**Comment by kleingeist** [comment]
lgtm

**Pull request merged**
