### PR TITLE
One task per mail

### PR DESCRIPTION
**Pull request by ihucos**

### CODE REVIEW

**Comment by ihucos** [comment]
Don't merge yet :-)

**Comment by ihucos** [comment]
Still needs a little bit of work and cleanup, but the future of newsletter mail sending is here :-)

You can see on the newsletter object how many mails where send and how many had errors
screenshot from 2018-05-31 18-00-07

with a simple click on the mail status you will be redirected to a more detailed status page
screenshot from 2018-05-31 18-03-26

and all mail is send in one task! no error handling needed

**Comment by treba123** [comment]
I'm not a dev but I'm against this. It doesn't scale well. What if we have 50k users? How long would it take to even schedule a task?

**Comment by ihucos** [comment]
> UNIX admin style 
Which I totally prefer in most cases, I am happy that we don't use too many cloudy external services.

**Comment by ihucos** [comment]
TODO: communicate too many mails in _from_ limitation

**Comment by ihucos** [comment]
This pull request adds django admin reporting to the newsletter with the ParallelEmailMixin
revert admin mail reporting before merging.
There is one limitation: all recepient mails together for one mail should not be bigger than 255 charachters

**Comment by ihucos** [comment]
I totally think we need this, but right now there is not so much time and in the future there also will not be, so I am closing this for now and hope that we can merge it another day.

**Pull request closed without merging**
