### PR TITLE
style radio buttons

### PR DESCRIPTION
**Pull request by vellip**

### CODE REVIEW

**Comment by 2e2a** [comment]
Looks nice.

But there is a problem with choices spanning over multiple lines:

radio_multiline

**Comment by vellip** [comment]
Good catch!

**Comment by xi** [comment]
This has some overlap with `.form-check`

**Comment by xi** [comment]
There is no focus indication with these radio boxes.

**Comment by xi** [comment]
b251c4c breaks the padding in the result view.

**Pull request merged**
