### PR TITLE
Pm 2020 11 cookie banner add

### PR DESCRIPTION
**Pull request by phillimorland**

### CODE REVIEW

**Review by fuzzylogic2000 — APPROVED** [review]
Nice! But could you add some comment, what this is used for? (and maybe also a comment where the the actual livestream is added to say what is added and when?)

**Comment by phillimorland** [comment]
It says in the file name, you think more documentation is needed? also should that be in all templates where it's added?

**Comment by fuzzylogic2000** [comment]
No, I just thought it is a good idea to say in this very long and overly complicated template, what the js is for. For the result or info tab, I think (or hope) it is more straightforward and easier to understand.

**Comment by phillimorland** [comment]
cool, will do! i'll also try add the test in this pull request :D

**Review by fuzzylogic2000 — APPROVED** [review]
Yeah!

**Pull request merged**
