### PR TITLE
update most dependencies to react 18

### PR DESCRIPTION
**Pull request by goapunk**

### CODE REVIEW

**Review by phillimorland — APPROVED** [review]
main is installing again, will merge and fix the react rendering

**Review by fuzzylogic2000 — COMMENTED** [review]
Yeah, it does install! But all react components do not work.

**Comment by fuzzylogic2000** [comment]
> main is installing again, will merge and fix the react rendering

Ah, cool!

**Review by fuzzylogic2000 — APPROVED** [review]
I also added shpjs now, but with that it works! Installing AND all the components. :)

**Pull request merged**
