### PR TITLE
Ks 2020 09 add interactive event module

### PR DESCRIPTION
**Pull request by Rineee**
The permission issue is fixed now. Because of [this code](https://github.com/liqd/adhocracy4/blob/3eb15d67f4de91aa004671a6813d5a847755d471/adhocracy4/api/permissions.py#L54) it was always asking for view_livequestions, but the permission was called view_questions, so renaming all permission was the solution.

So now you can add an interactive event and view it and post questions, but the whole react part looks very messy and I am not even sure if everything works there.. but maybe this is something for @phillimorland to go on with? :)

### CODE REVIEW

**Comment by Rineee** [comment]
The permission issue is fixed now. Because of [this code](https://github.com/liqd/adhocracy4/blob/3eb15d67f4de91aa004671a6813d5a847755d471/adhocracy4/api/permissions.py#L54) it was always asking for view_livequestions, but the permission was called view_questions, so renaming all permission was the solution.

The whole react part looks very messy and I am not even sure if everything works there.. but maybe this is something for @phillimorland? :)

**Review by fuzzylogic2000 — CHANGES_REQUESTED** [review]
The project tile and the view from the dashboard doesn't link to the view: 
```
django.urls.exceptions.NoReverseMatch: Reverse for 'module-detail' with arguments '('liqd', 'interactive-event')' not found. 1 pattern(s) tried: ['projekte/module/(?P<module_slug>[-\\w_]+)/$']
```

**Review by fuzzylogic2000 — APPROVED** [review]

**Comment by fuzzylogic2000** [comment]
@phillimorland Alright, do you want to go on in this PR or do we just merge (while it still looks pretty broken)?

**Comment by phillimorland** [comment]
@fuzzylogic2000 @Rineee I have started doing a clean up and it now doesn't look so broken, so we can maybe merge now and then keep working on different parts?

**Review by fuzzylogic2000 — APPROVED** [review]
Yes! I like that, let's do that!

**Pull request merged**
