### PR TITLE
fix category save issue and bump release

### PR DESCRIPTION
**Pull request by goapunk**
**Describe your changes**
Briefly explain what you did and provide context for a clearer understanding.

**Tasks**
- [ ] PR name contains story or task reference
- [ ] Steps to recreate and test the changes
- [ ] Documentation (docs and inline)
- [ ] Tests (including n+1 and django_assert_num_queries where applicable)
- [x] Changelog

### CODE REVIEW

**Review by m4ra — APPROVED** [review]
thanks!

**Review by m4ra — CHANGES_REQUESTED** [review]
oh there is an error with react-leaflet for the maps

**Comment by goapunk** [comment]
> oh there is an error with react-leaflet for the maps

oh, right, we haven't updated a4 for a while :/ will push a fix but I guess we should test this a bit longer

**Comment by m4ra** [comment]
@goapunk can you ping the test team then? I am gonna merge this PR now

**Pull request merged**
