### PR TITLE
Ks 2021 12 token voting permissions

### PR DESCRIPTION
**Pull request by Rineee**
I did some more research and decided to not use rules for the token voting api permissions as rules are dependent on users and arent really useful here. 
I instead introduced a new Permission class, called TokenVotePermission that checks manually the relevant requirements on the token for create and destroy actions.
Also, I added a check in TokenVoteMixin to make sure that the token is valid before anything else is checked.

### CODE REVIEW

**Comment by Rineee** [comment]
@fuzzylogic2000 Now I remember why I also wanted to add the phase to the serializer, we also use the isVotingPhase for not showing the rating here: https://github.com/liqd/a4-meinberlin/blob/d69a4dd624705c7f28a053e123e0dcdf847fbe3d/meinberlin/apps/budgeting/assets/BudgetingProposalListItem.jsx#L23 
Not sure how to deal with it if not with serializer info, do you have an idea?

**Comment by fuzzylogic2000** [comment]
> @fuzzylogic2000 Now I remember why I also wanted to add the phase to the serializer, we also use the isVotingPhase for not showing the ratings here:
> 
> https://github.com/liqd/a4-meinberlin/blob/d69a4dd624705c7f28a053e123e0dcdf847fbe3d/meinberlin/apps/budgeting/assets/BudgetingProposalListItem.jsx#L23
> 
> Not sure how to deal with it if not with serializer info, do you have an idea?

So, the decision was to just keep it in the template tag for now, right?

**Comment by Rineee** [comment]
> > @fuzzylogic2000 Now I remember why I also wanted to add the phase to the serializer, we also use the isVotingPhase for not showing the ratings here:
> > https://github.com/liqd/a4-meinberlin/blob/d69a4dd624705c7f28a053e123e0dcdf847fbe3d/meinberlin/apps/budgeting/assets/BudgetingProposalListItem.jsx#L23
> > 
> > Not sure how to deal with it if not with serializer info, do you have an idea?
> 
> So, the decision was to just keep it in the template tag for now, right?

Yes! Should I write an issue to think about moving it to the api?

**Review by phillimorland — COMMENTED** [review]
install and passing tests but vote button functioonality no longer working, is this expected?

**Comment by Rineee** [comment]
> install and passing tests but vote button functioonality no longer working, is this expected?

@phillimorland No, that should work still! What does it say in the network tab?

**Comment by phillimorland** [comment]
@Rineee ignore me, I forgot I had to re-enter my token :p however I will add that we must disable hover styling on the disabled vote button

**Pull request merged**
