### PR TITLE
[8450] update django-allauth

### PR DESCRIPTION
**Pull request by goapunk**
**Describe your changes**
Update django-allauth to latest version and adapt to changes. Remove the unused social settings and forms.

**Tasks**
- [x] PR name contains story or task reference
- [ ] Steps to recreate and test the changes
- [ ] Documentation (docs and inline)
- [ ] Tests (including n+1 and django_assert_num_queries where applicable)
- [x] Changelog

### CODE REVIEW

**Comment by goapunk** [comment]
> if socialaccount is not used, then lets remove it also from the settings INSTALLED_APPS.
yes, good point!

> There is also a change on how the user is logged in after clicking the link `Verifying the email address by clicking on the link would no longer log you in, even in case of ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True.` from [changelog](https://github.com/pennersr/django-allauth/blob/main/ChangeLog.rst#6421-2024-09-05). Good to add this in the changelog maybe? We need to inform also PM?

To me this reads like a bugfix, they fixed that `ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION=True` is now working again as intended after it broke in a previous release, so the intended behaviour still the same. I will test if the bug is on stage and if it behaves different to this PR. If it's the same I guess we don't need to tell PMs

**Comment by goapunk** [comment]
@m4ra I tested the behaviour on stage against this PR and for both you get automatically logged in when verifying your email, so I think we missed the version of allauth where it broke :)

**Comment by m4ra** [comment]
@goapunk I tested already on stage, and logs you in after verifying email. So should be fine

**Comment by goapunk** [comment]
> @goapunk I tested already on stage, and logs you in after verifying email. So should be fine

ah, thanks!

**Review by m4ra — APPROVED** [review]
thanks!

**Comment by goapunk** [comment]
@m4ra hmm, now the tests are failing :/ maybe I leave the social account stuff in for now ? We usually have the policy to remove unused code but also this might be out of scope for the release story

**Comment by m4ra** [comment]
Leave it out yes. Maybe create an gh issue

**Comment by goapunk** [comment]
created https://github.com/liqd/a4-meinberlin/issues/5828

**Review by m4ra — APPROVED** [review]

**Pull request merged**
