### PR TITLE
Ka 2020 11 group members

### PR DESCRIPTION
**Pull request by fuzzylogic2000**

### CODE REVIEW

**Comment by rmader** [comment]
@fuzzylogic2000: is this still WIP?

**Comment by fuzzylogic2000** [comment]
@rmader Yes, again. I wanted to do another issue and add some tests.

**Comment by rmader** [comment]
Oh right, didn't see you changed it back to WIP after requesting the review :)

**Comment by fuzzylogic2000** [comment]
@Rineee @rmader I only wanted to test the newly fixed issue, but turns out, that the dashboard views were still untested. (and list and delete still are, but well, that's for another day!)

**Review by Rineee — APPROVED** [review]
Wohooo, great!

**Pull request merged**
