### PR TITLE
Kl 2021 11 more propsal api filters

### PR DESCRIPTION
**Pull request by fuzzylogic2000**
This does the filtering. But we need to know which categories to display (and their icons). 
What is the best way to add that? I think previously we either added that to the template tag or to the serializer. But I guess the best option would be to add it to the response.data of the API, which should be possible? What do you think @Rineee ?

### CODE REVIEW

**Comment by fuzzylogic2000** [comment]
> This does the filtering. But we need to know which categories to display (and their icons). What is the best way to add that? I think previously we either added that to the template tag or to the serializer. But I guess the best option would be to add it to the response.data of the API, which should be possible? What do you think @Rineee ?

And wherever we put the category choices, the moderator feedback choices should also go there. (Or of course stay where they are and we also put the category choices there.) https://github.com/liqd/a4-meinberlin/blob/fce4f4d47491cc78d0420c0684fa8c96e987a7b6/meinberlin/apps/budgeting/serializers.py#L73 What do we actually need them for, though?

**Comment by khamui** [comment]
> > This does the filtering. But we need to know which categories to display (and their icons). What is the best way to add that? I think previously we either added that to the template tag or to the serializer. But I guess the best option would be to add it to the response.data of the API, which should be possible? What do you think @Rineee ?
> 
> And wherever we put the category choices, the moderator feedback choices should also go there. (Or of course stay where they are and we also put the category choices there.)
> 
> https://github.com/liqd/a4-meinberlin/blob/fce4f4d47491cc78d0420c0684fa8c96e987a7b6/meinberlin/apps/budgeting/serializers.py#L73
> 
> What do we actually need them for, though?

yes i was not sure where to add the choices best.
It is used here:
https://github.com/liqd/a4-meinberlin/blob/fce4f4d47491cc78d0420c0684fa8c96e987a7b6/meinberlin/apps/budgeting/assets/ListItemBadges.jsx#L7

**Comment by khamui** [comment]
yeah nice! can be filtered on the api

**Comment by Rineee** [comment]
@fuzzylogic2000 @khamui I will look into where/how to add the choices best!

**Pull request merged**
