### PR TITLE
translations: adjusting 'make po' command in Makefile to work with...

### PR DESCRIPTION
**Pull request by khamui**
…mac os and ubuntu.

To be tested in macOS and linux (ubuntu).

### CODE REVIEW

**Comment by khamui** [comment]
@phillimorland can you please test this if the `make po` command works for both macOs and ubuntu (you are the chosen one because you have the power of both OS right)?

**Comment by phillimorland** [comment]
I am! so mac is good btu for ubuntu I get 
`sed -i '' 's%#: .*/adhocracy4%#: adhocracy4%' locale/*/LC_MESSAGES/django*.po
sed: can't read s%#: .*/adhocracy4%#: adhocracy4%: No such file or directory
make: *** [Makefile:130: po] Error 2`

**Review by phillimorland — CHANGES_REQUESTED** [review]
see comment :)

**Comment by fuzzylogic2000** [comment]
So, no, this does not work in most of our shells. Maybe @goapunk has an idea? It's about the sed command (see Files changed), which in @khamui zshell only works with the empty string added at front. Is there a way for the Makefile to test in which shell it is used?
Otherwise @khamui you could change it in your Makefile every time and not commit it or use another shell for the make po command?

**Comment by khamui** [comment]
okay i pushed another version which adds this workaround (empty string) for macOS, but keeps it without for all other operating systems. I could remove the linux case and keep * for all others. @phillimorland if this would work for macOs and LInux for you we could go with that?

Otherwise i will just change that everytime for me as @fuzzylogic2000 proposed.

**Comment by goapunk** [comment]
this shouldn't be necessary if you install gsed on mac (brew install gnu-sed), maybe we should document this somewhere.

**Comment by khamui** [comment]
as @goapunk stated above, i removed that fix. And instead mac users should install gsed and all works fine! I added a comment to mention this. Not sure if this is enough.

**Review by fuzzylogic2000 — APPROVED** [review]
Nice! And I think we will remember this. :)

**Pull request merged**
