### PR TITLE
input action element

### PR DESCRIPTION
**Pull request by vellip**
To have an input and an action next to each other.

screen shot 2017-05-12 at 18 33 10

### CODE REVIEW

**Comment by xi** [comment]
@damusp also noted that the choice fields should not fill the full available width.

**Comment by xi** [comment]
screenshot from 2017-05-15 18-17-14

I pushed a version that uses light buttons. Feel free to revert if you do not like it.

**Comment by damusp** [comment]
but i like it!

**Comment by vellip** [comment]
The width shouldn't be a part of this element. Your changes are fine with me.

**Pull request merged**
