### PR TITLE
#2769 templates/progress_line: adding progress line with some styling and s…

### PR DESCRIPTION
**Pull request by phillimorland**
…ome if statements
@fuzzylogic2000 this is what I got so far

### CODE REVIEW

**Comment by fuzzylogic2000** [comment]
Nice! Do you want to style more and then we do the other stuff or should I already have a go?
Oh, I know, I will just branch of your branch and we might have to learn more git in the end. :) I mean, we will have to tackle the rebase! Most exciting thing for that day then

**Comment by phillimorland** [comment]
@fuzzylogic2000 I was waiting for a design on the published project but Caro's going to send me something but I changed the dots a bit as the first one is always completed as the creation has happened so added that and swapped the line and added the 3 dot types. (hope thats what you meant!)

**Comment by fuzzylogic2000** [comment]
@phillimorland I added all the logic, but our dashboard gets more and more crazy. If this works, I still think you should merge for us to test it and talk about it!

**Comment by phillimorland** [comment]
@fuzzylogic2000 i'm not sure on the active behavior but it's working :)

**Pull request merged**
