### PR TITLE
Added ellipsis for maps pop up

### PR DESCRIPTION
**Pull request by ihucos**
**Before**
screenshot from 2018-05-14 18-35-15

**After**
screenshot from 2018-05-14 18-34-58

### CODE REVIEW

**Comment by ihucos** [comment]
A little out of process..... but nice

**Comment by fuzzylogic2000** [comment]
Yeah! I was so sure this didn't work for two lines, but it works differently than I thought. Still nice. But as we do not cut off long texts, using word-break might be a better idea? I just commited that to your branch. Revert if you find your option better.
It would actually be awesome if the text would break like in my commit, but then be ellipsed after two lines. I couldn't find an easy solution for that, though. So let's hope for sensible users with short idea titles (with long words if they like). :)

**Comment by ihucos** [comment]
Yeah, it's also good, I think both are much better then it was before. I don't know if hyphenation (silbentrennung) is an issue at all.

**Comment by ihucos** [comment]
screenshot from 2018-05-15 09-44-49

**Pull request merged**
