### PR TITLE
Kl 2021 07 poll translations

### PR DESCRIPTION
**Pull request by fuzzylogic2000**
I got this error when extracting the strings to translate, but couldn't find the reason:
```
~/a4-meinberlin/venv/bin/python manage.py makemessages -d djangojs
~/a4-meinberlin/node_modules/adhocracy4/adhocracy4/polls/assets/PollOpenQuestion.jsx:39: warning: RegExp literal terminated too early
```

depends on https://github.com/liqd/adhocracy4/pull/774

### CODE REVIEW

**Comment by fuzzylogic2000** [comment]
Alright! That's all the translations for now and the first commit can be fixed, once the PR in a4 is merged! :tada:

**Review by Rineee — APPROVED** [review]
Thank you for translating all my validation messages <3 !

**Comment by Rineee** [comment]
@fuzzylogic2000 I have a PR that is also updating A4, but with an older commit.. should we merge that first? So we dont go back to the older one then? https://github.com/liqd/a4-meinberlin/pull/3713

**Comment by fuzzylogic2000** [comment]
> @fuzzylogic2000 I have a PR that is also updating A4, but with an older commit.. should we merge that first? So we dont go back to the older one then? #3713

I was just wondering about that. :) It's merged!

**Comment by fuzzylogic2000** [comment]
Right, and I will fix this!

**Comment by Rineee** [comment]
> Right, and I will fix this!

Haha, was just going to say I will, but you were quicker!

**Pull request merged**
