### PR TITLE
Kl 2021 06 use polls fom a4

### PR DESCRIPTION
**Pull request by fuzzylogic2000**
Don't forget to save your DB before trying this out! (and maybe add some "old" polls before you check this out and save it)

### CODE REVIEW

**Comment by fuzzylogic2000** [comment]
Heureka! here is the migration! @Rineee Maybe you can already have a look? Now we only have to use the stuff from a4 to be able to see the data from outside of the shell or DB as well...

**Comment by fuzzylogic2000** [comment]
Oh, and I think, we should try the migration on prod-data as well. :grimacing: Will need some help for that. @goapunk @Rineee :smile_cat:

**Comment by goapunk** [comment]
> Oh, and I think, we should try the migration on prod-data as well. grimacing Will need some help for that. @goapunk @Rineee smile_cat
sure :)

**Review by Rineee — APPROVED** [review]
Looking good! I migrated my polls and everything is fine.. should we dare to merge? :scream:

**Comment by fuzzylogic2000** [comment]
> Looking good! I migrated my polls and everything is fine.. should we dare to merge? scream

@goapunk Did you save the database? In that case, I would say: go for it!

**Comment by fuzzylogic2000** [comment]
Oh, and @CarolingerSeilchenspringer Do you already have old-poll-test-projects? We shouldn't merge before...

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 didn't know it was so urgent, will do it right away.

**Pull request merged**
