### PR TITLE
Filter UI

### PR DESCRIPTION
**Pull request by xi**
Building on #86, this changes UI to be more in line with the previous sorting UI. There is still room for improvement:

-   style the dropdown buttons (similar to select, withy max-width and text-overflow)
-   improve UI in cases where there are many filters (especially on mobile)

### CODE REVIEW

**Comment by 2e2a** [comment]
If no ordering is selected 'All' is shown instead of the first choice.

**Comment by 2e2a** [comment]
The filter and ordering elements do not have the same vertical position.
We could fix this later, but I think having this fixed would make the initial version look already much better.

**Comment by xi** [comment]
> The filter and ordering elements do not have the same vertical position.

I thought I took care of that. Are you sure that you did run webpack?

**Comment by 2e2a** [comment]
>> The filter and ordering elements do not have the same vertical position.

> I thought I took care of that. Are you sure that you did run webpack?

Apparently not ... Ignore this comment.

**Comment by 2e2a** [comment]
lgtm

**Pull request merged**
