### PR TITLE
Ka 2018 01 use distinct ordering filter

### PR DESCRIPTION
**Pull request by fuzzylogic2000**
Uses the distinct ordering filters from a4.

I searched for ListViews with pagination not using the ordering filter. I found:
- Actions -- use timestamp for ordering
- LogEntry -- also timestamp
- Dashboard2 -- uses a filterset, but currently without ordering filter. I guess, we will remember for a wile that we have to be careful if we add one, but should we put that down somewhere as well? or hope, that django filters fixes it before it can go wrong? To order, it uses created
- ProjectContainers -- uses pagination, but I couldn't find an ordering. But this is shown in the normal project list view and ordered?! I can only find how the projects from the containers are filtered out of the project list view, not how the containers are put into the list.

### CODE REVIEW

**Comment by kleingeist** [comment]
@fuzzylogic2000 
so we should give them ListViews an distinct ordering, too? 
should we add them to this PR?

**Comment by fuzzylogic2000** [comment]
@kleingeist Yes, I think so. But I hoped timetsamp and created would be distinct enough?! Or we just add the pk to every ordering to make sure nothing can ever go wrong.
And what about the ProjectContainers? Do they get the ordering somewhere?

**Comment by kleingeist** [comment]
yes i think it is okay to regard timestamps with microsends as distinct. 
what do you mean by project containers? you mean the projects within the container? they should get the default ordering from `Project` which is `created`

**Comment by fuzzylogic2000** [comment]
As the models used in the views then all have a distinct ordering, I think we're fine?!

**Comment by kleingeist** [comment]
did try on a few examples but i don't have enough ideas created for testing. couldn't find a problem. will merge and see what happens on the server :)

**Pull request merged**
