### PR TITLE
Filter ideas by category

### PR DESCRIPTION
**Pull request by 2e2a**
Requires: https://github.com/liqd/adhocracy4/pull/39

Open issues:

- The filtering/sorting parameters  do not work with pagination and will be fixed separately
- form needs to be styled
- Do not display empty filter (e.g. no categories)

### CODE REVIEW

**Comment by xi** [comment]
LGTM.

**Comment by xi** [comment]
I experimented a bit with the UI: 1cd36ba. This commit is not really ready for production, but it might be a useful reference.

**Comment by xi** [comment]
I noticed that django-filter does have a `ModelMultipleChoiceFilter` class, so ORing several categories should not be that hard to implement.

**Comment by 2e2a** [comment]
> I noticed that django-filter does have a ModelMultipleChoiceFilter class, so ORing several categories should not be that hard to implement.

Thats good to know. Will keep it in mind, if we need to extend the filter.

**Pull request merged**
