### PR TITLE
apps/budgeting: add anchor link and use in list

### PR DESCRIPTION
**Pull request by fuzzylogic2000**

### CODE REVIEW

**Review by phillimorland — COMMENTED** [review]
the page anchor should work looking at the code but it's not and I don't know why? tested on ff and chrome
also we can add `scroll-behavior: smooth;` to html to ensure it's not stuttery

**Comment by fuzzylogic2000** [comment]
> the page anchor should work looking at the code but it's not and I don't know why? tested on ff and chrome also we can add `scroll-behavior: smooth;` to html to ensure it's not stuttery

@phillimorland It did work in Chromium. Will try again and add the smooth-thingy though!

**Review by fuzzylogic2000 — COMMENTED** [review]
@khamui Nice! For me it only works when there are multiple proposals in the list? 
Would be cool, if you could make one commit of the two.
And maybe @phillimorland can also review?

**Review by phillimorland — COMMENTED** [review]
yep looks good, it works but the scroll to view almost scrolls too far so the top of the content is already going off screen

**Comment by khamui** [comment]
@phillimorland about the offset (top edge) we decided to go with a small offset for now. In case there needs to be a positioning in the center, this would be a story for later with a design.

**Comment by fuzzylogic2000** [comment]
Alright! Talked to @phillimorland and wil merge!

**Pull request merged**
