### PR TITLE
[5929] apps/plans: add explanation to export

### PR DESCRIPTION
**Pull request by fuzzylogic2000**
I used mB with Node 16 and the legacy-install.

### CODE REVIEW

**Comment by phillimorland** [comment]
@fuzzylogic2000 to get it running I tried:
`nvm install v16`
`npm install --legacy-peer-deps`
`make watch`
was that it or did I miss a step?

**Comment by fuzzylogic2000** [comment]
> @fuzzylogic2000 to get it running I tried: `nvm install v16` `npm install --legacy-peer-deps` `make watch` was that it or did I miss a step?

@phillimorland I deleted everything before doing that. So,
```
npm cache clean --force
make clean
nvm use v16
npm install --legacy-peer-deps
make install
make watch
```
I hope, that works!?

**Comment by phillimorland** [comment]
@fuzzylogic2000 thanks for pointer, still won't run `make install` for me :(

**Comment by fuzzylogic2000** [comment]
Gah, well, maybe we can just merge, so it can be tested on dev? @phillimorland

**Pull request merged**
