### PR TITLE
 apps/plans: Remember closing the infobox on sticky map 

### PR DESCRIPTION
**Pull request by rmader**
and some ES6 conversion, as that made it easier.

Based on this tutorial: https://medium.com/@rossbulat/using-cookies-in-react-redux-and-react-router-4-f5f6079905dc

Hopefully doesn't break anything jquery related in other places...

### CODE REVIEW

**Comment by rmader** [comment]
The meat of this MR is actually the changes in `meinberlin/apps/plans/assets/PlansMap.jsx`, so that's what really needs review.

**Comment by fuzzylogic2000** [comment]
I get the same error. 
And was wondering: I guess, we need to thoroughly test it in all browsers (IE11!)?! Did you already do that?

**Comment by rmader** [comment]
Ah right, should work now and the solution is now even cleaner. Will test with IE11 tomorrow, but I'd assume react-cookie works there, too.

**Comment by rmader** [comment]
Just deployed this branch on dev and tested with browserstack. Works on IE11 and safari :)
Any concerns left or can we merge this? :) @MagdaN @fuzzylogic2000

**Pull request merged**
