### PR TITLE
editorconfig: skip migrations for isort

### LINKED ISSUE #3234: exclude migratiuons from lint-python-files
**URL:** 
**user:** 
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

### PR DESCRIPTION
**Pull request by fuzzylogic2000**
fixes #3234 
https://github.com/PyCQA/isort/issues/885#issuecomment-552069021
https://pycqa.github.io/isort/docs/configuration/options/#skip-glob
https://github.com/PyCQA/isort/issues/885

### CODE REVIEW

**Comment by Rineee** [comment]
Did you also already try this --filter-files option: https://github.com/PyCQA/isort/issues/885#issuecomment-552069021 ?
If not, maybe that works? I could try it out, if you want..

**Comment by fuzzylogic2000** [comment]
Awesome! I will try that later, thank you! @Rineee

**Comment by fuzzylogic2000** [comment]
@Rineee NIce! That did work! 
I also changed --df to --diff for the sake of being the same as in make lint. They both do the same.

**Comment by rmader** [comment]
Oh nice!

**Review by rmader — APPROVED** [review]

**Review by Rineee — APPROVED** [review]
Super nice!

**Pull request merged**
