### PR TITLE
[#4987]budgeting: add proposal serializer and api

### PR DESCRIPTION
**Pull request by Rineee**
The url to get the proposals is `reverse('proposals-list', kwargs={'module_pk': $module_pk})` or `/api/modules/$module_pk/proposals/` which we then probably need to add to context of ProposalListView

### CODE REVIEW

**Comment by phillimorland** [comment]
>  `/api/modules/$module_pk/proposals/`

dumb question: how to find a module_pk?

**Review by phillimorland — COMMENTED** [review]
I am not getting a list of my ideas, the api does have an endpoint (think thats the right word) but the list is empty despite having 3 ideas added, I feel this is not what was intended?

**Comment by Rineee** [comment]
> I am not getting a list of my ideas, the api does have an endpoint (think thats the right word) but the list is empty despite having 3 ideas added, I feel this is not what was intended?

Ok weird, it does work for me, I just checked again.. but you are looking at a Bürgerhaushalt, right? Because it is only showing proposals, not ideas..

**Comment by phillimorland** [comment]
> > I am not getting a list of my ideas, the api does have an endpoint (think thats the right word) but the list is empty despite having 3 ideas added, I feel this is not what was intended?
> 
> @phillimorland Ok weird, it does work for me, I just checked again.. but you are looking at a Bürgerhaushalt, right? Because it is only showing proposals, not ideas..

**Review by phillimorland — APPROVED** [review]
sorry closed by mistake.
Yep works when I have the correct PK, sorry! and yey perfect!

**Pull request merged**
