### PR TITLE
[7008]apps/budgeting/vote-button: only show vote button if has sessio…

### PR DESCRIPTION
**Pull request by khamui**
…n token and in right phase (list item and detail)

### CODE REVIEW

**Comment by phillimorland** [comment]
@khamui this overlaps with @Rineee permissions PR so will just place this on hold for now until that one has been cleared up

**Comment by Rineee** [comment]
Setting this to WIP as https://github.com/liqd/a4-meinberlin/pull/4901 should be merged first and then the getting of voting token should be adjusted.

**Comment by Rineee** [comment]
@phillimorland This should be ready now!

**Review by phillimorland — APPROVED** [review]
awesome! :)

**Pull request merged**
