### PR TITLE
simple user profile

### PR DESCRIPTION
**Pull request by xi**
This adds a simple user profile. Its main purpose is to fix the broken links on comments.

The information that is shown is username, join date and followed projects. Is this ok or should we keep some of that information private?

The implementation is based on a4-opin. I am not completely sure whether the selection of projects is useful in our context. Maybe it would also be good to ignore archived projects to not end up with hundrets o projects over time.

### CODE REVIEW

**Comment by kleingeist** [comment]
lgtm
@xi do you want to review my changes and then merge this PR?

**Comment by vellip** [comment]
Just a minor remark, maybe make the `h2` something like "Projects {{user}} participated in".

**Comment by vellip** [comment]
Guys, Travis seems to keep failing here.

**Comment by xi** [comment]
I think it fails because the PR was merged before travis could start. My bad.

**Pull request merged**
