### PR TITLE
base.py: rm testing embed from other ckeditors, ck_embed: add styling…

### PR DESCRIPTION
**Pull request by phillimorland**
… for ck embed

### CODE REVIEW

**Review by fuzzylogic2000 — COMMENTED** [review]
It looks great where the video already is, but now the button to add the video is gone?! :crying_cat_face:

**Comment by phillimorland** [comment]
@fuzzylogic2000 just tested this on a new project but cannot reproduce, you did try in the information field in project right? on what browser?

**Comment by Rineee** [comment]
I just checked it and I have to button to add the videos..?

**Comment by fuzzylogic2000** [comment]
Oh, weird. If it was also fine for @rine, then just merge (and I will check again on dev later). :)

**Pull request merged**
