### PR TITLE
Fix MapIdea export

### PR DESCRIPTION
**Pull request by kleingeist**
MapIdeas have not ModeratorFeedback

### CODE REVIEW

**Comment by kleingeist** [comment]
verhalten kann gerade noch nicht ganz nachvollzogen werden

**Comment by 2e2a** [comment]
lgtm

**Comment by kleingeist** [comment]
okay it _is_ reproducible. 
one mapidea project which i tried to export did not have any ideas, so the error did not occur
@2e2a can be merged

**Comment by 2e2a** [comment]
lgtm

**Pull request merged**
